/// Flutter icons CustomIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcon
///      fonts:
///       - asset: fonts/CustomIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcon {
  CustomIcon._();

  static const _kFontFam = 'CustomIcon';
  static const _kFontPkg = null;

  static const IconData one = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData two = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData three = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData four = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData five = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData six = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData seven = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eight = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nine = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ten = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eleven = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twelve = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thirteen = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fourteen = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fiftheen = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
